ARG  VERSION_NUMBER
FROM cytomine/pims-plugin-format-dicom-dependencies:v$VERSION_NUMBER

RUN pip3 install pytest
RUN pip3 install -e /app

RUN mkdir -p /data/pims/upload_test_wsidicom

COPY ./ci/app/tests /app/tests

RUN ls /app/

RUN ls /app/tests

CMD pytest -rP /app/plugins/pims-plugin-format-dicom/tests --junit-xml=ci/test-reports/pytest_unit.xml
